
SOURCES += \
    kImageAnnotator/src/annotations/core/AnnotationArea.cpp \
    kImageAnnotator/src/annotations/core/AnnotationItemFactory.cpp \
    kImageAnnotator/src/annotations/core/AnnotationPropertiesFactory.cpp \
    kImageAnnotator/src/annotations/items/helper/CapsLockStatusChecker.cpp \
    kImageAnnotator/src/annotations/items/helper/KeyInputHelper.cpp \
    kImageAnnotator/src/annotations/items/helper/TextCursor.cpp \
    kImageAnnotator/src/annotations/items/AbstractAnnotationItem.cpp \
    kImageAnnotator/src/annotations/items/AbstractAnnotationLine.cpp \
    kImageAnnotator/src/annotations/items/AbstractAnnotationPath.cpp \
    kImageAnnotator/src/annotations/items/AbstractAnnotationRect.cpp \
    kImageAnnotator/src/annotations/items/AnnotationArrow.cpp \
    kImageAnnotator/src/annotations/items/AnnotationBlur.cpp \
    kImageAnnotator/src/annotations/items/AnnotationDoubleArrow.cpp \
    kImageAnnotator/src/annotations/items/AnnotationEllipse.cpp \
    kImageAnnotator/src/annotations/items/AnnotationLine.cpp \
    kImageAnnotator/src/annotations/items/AnnotationNumber.cpp \
    kImageAnnotator/src/annotations/items/AnnotationPen.cpp \
    kImageAnnotator/src/annotations/items/AnnotationRect.cpp \
    kImageAnnotator/src/annotations/items/AnnotationText.cpp \
    kImageAnnotator/src/annotations/misc/AbstractCloneableItemEffect.cpp \
    kImageAnnotator/src/annotations/misc/AnnotationContextMenu.cpp \
    kImageAnnotator/src/annotations/misc/AnnotationItemClipboard.cpp \
    kImageAnnotator/src/annotations/misc/ImageBlurrer.cpp \
    kImageAnnotator/src/annotations/misc/NumberManager.cpp \
    kImageAnnotator/src/annotations/misc/ShadowEffect.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/AbstractItemResizeHandles.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/AbstractRectResizeHandles.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/LineResizeHandles.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/PathResizeHandles.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/RectResizeHandles.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/ResizeHandle.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/ResizeHandlesFactory.cpp \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemArranger.cpp \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemModifier.cpp \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemMover.cpp \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemResizer.cpp \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemSelector.cpp \
    kImageAnnotator/src/annotations/modifiers/AnnotationMultiItemResizer.cpp \
    kImageAnnotator/src/annotations/properties/AnnotationBlurProperties.cpp \
    kImageAnnotator/src/annotations/properties/AnnotationPathProperties.cpp \
    kImageAnnotator/src/annotations/properties/AnnotationProperties.cpp \
    kImageAnnotator/src/annotations/properties/AnnotationTextProperties.cpp \
    kImageAnnotator/src/annotations/undo/AddCommand.cpp \
    kImageAnnotator/src/annotations/undo/ArrangeCommand.cpp \
    kImageAnnotator/src/annotations/undo/CropCommand.cpp \
    kImageAnnotator/src/annotations/undo/DeleteCommand.cpp \
    kImageAnnotator/src/annotations/undo/MoveCommand.cpp \
    kImageAnnotator/src/annotations/undo/PasteCommand.cpp \
    kImageAnnotator/src/annotations/undo/ResizeCommand.cpp \
    kImageAnnotator/src/annotations/undo/ScaleCommand.cpp \
    kImageAnnotator/src/annotations/undo/UndoStack.cpp \
    kImageAnnotator/src/backend/Config.cpp \
    kImageAnnotator/src/common/filter/IgnoreShortcutsFilter.cpp \
    kImageAnnotator/src/common/helper/ConfigNameHelper.cpp \
    kImageAnnotator/src/common/helper/CursorHelper.cpp \
    kImageAnnotator/src/common/helper/IconLoader.cpp \
    kImageAnnotator/src/common/helper/ItemHelper.cpp \
    kImageAnnotator/src/common/helper/KeyHelper.cpp \
    kImageAnnotator/src/common/helper/MathHelper.cpp \
    kImageAnnotator/src/common/helper/ShapeHelper.cpp \
    kImageAnnotator/src/gui/annotator/AnnotationWidget.cpp \
    kImageAnnotator/src/gui/annotator/WidgetConfigurator.cpp \
    kImageAnnotator/src/gui/cropper/CropHandles.cpp \
    kImageAnnotator/src/gui/cropper/CropSelectionHandler.cpp \
    kImageAnnotator/src/gui/cropper/CropSelectionMoveHelper.cpp \
    kImageAnnotator/src/gui/cropper/CropSelectionRestrictor.cpp \
    kImageAnnotator/src/gui/cropper/CropView.cpp \
    kImageAnnotator/src/gui/cropper/CropWidget.cpp \
    kImageAnnotator/src/gui/scaler/ScaleDialog.cpp \
    kImageAnnotator/src/gui/scaler/ScaleSizeHandler.cpp \
    kImageAnnotator/src/gui/scaler/ScaleWidget.cpp \
    kImageAnnotator/src/gui/CoreView.cpp \
    kImageAnnotator/src/gui/KImageAnnotator.cpp \
    kImageAnnotator/src/widgets/ColorPicker.cpp \
    kImageAnnotator/src/widgets/CustomSpinBox.cpp \
    kImageAnnotator/src/widgets/CustomToolButton.cpp \
    kImageAnnotator/src/widgets/CustomToolButtonAction.cpp \
    kImageAnnotator/src/widgets/FillTypePicker.cpp \
    kImageAnnotator/src/widgets/NumberPicker.cpp \
    kImageAnnotator/src/widgets/ToolPicker.cpp \
    kImageAnnotator/src/annotations/items/annotationpolygon.cpp \
    kImageAnnotator/src/annotations/items/abstractannotationpolygon.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/polygonresizehandles.cpp \
    kImageAnnotator/src/annotations/items/abstractannotationNumberGroup.cpp \
    kImageAnnotator/src/annotations/items/annotationNumberGroup.cpp \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/NumberGroupresizehandles.cpp

HEADERS += \
    kImageAnnotator/include/kImageAnnotator/KImageAnnotator.h \
    kImageAnnotator/include/kImageAnnotator/KImageAnnotatorExport.h \
    kImageAnnotator/src/annotations/core/AnnotationArea.h \
    kImageAnnotator/src/annotations/core/AnnotationItemFactory.h \
    kImageAnnotator/src/annotations/core/AnnotationPropertiesFactory.h \
    kImageAnnotator/src/annotations/items/helper/CapsLockStatusChecker.h \
    kImageAnnotator/src/annotations/items/helper/KeyInputHelper.h \
    kImageAnnotator/src/annotations/items/helper/TextCursor.h \
    kImageAnnotator/src/annotations/items/helper/TextPositions.h \
    kImageAnnotator/src/annotations/items/AbstractAnnotationItem.h \
    kImageAnnotator/src/annotations/items/AbstractAnnotationLine.h \
    kImageAnnotator/src/annotations/items/AbstractAnnotationPath.h \
    kImageAnnotator/src/annotations/items/AbstractAnnotationRect.h \
    kImageAnnotator/src/annotations/items/AnnotationArrow.h \
    kImageAnnotator/src/annotations/items/AnnotationBlur.h \
    kImageAnnotator/src/annotations/items/AnnotationDoubleArrow.h \
    kImageAnnotator/src/annotations/items/AnnotationEllipse.h \
    kImageAnnotator/src/annotations/items/AnnotationLine.h \
    kImageAnnotator/src/annotations/items/AnnotationNumber.h \
    kImageAnnotator/src/annotations/items/AnnotationPen.h \
    kImageAnnotator/src/annotations/items/AnnotationRect.h \
    kImageAnnotator/src/annotations/items/AnnotationText.h \
    kImageAnnotator/src/annotations/misc/AbstractCloneableItemEffect.h \
    kImageAnnotator/src/annotations/misc/AnnotationContextMenu.h \
    kImageAnnotator/src/annotations/misc/AnnotationItemClipboard.h \
    kImageAnnotator/src/annotations/misc/ImageBlurrer.h \
    kImageAnnotator/src/annotations/misc/NumberManager.h \
    kImageAnnotator/src/annotations/misc/ShadowEffect.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/AbstractItemResizeHandles.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/AbstractRectResizeHandles.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/LineResizeHandles.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/PathResizeHandles.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/RectResizeHandles.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/ResizeHandle.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/ResizeHandlesFactory.h \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemArranger.h \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemModifier.h \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemMover.h \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemResizer.h \
    kImageAnnotator/src/annotations/modifiers/AnnotationItemSelector.h \
    kImageAnnotator/src/annotations/modifiers/AnnotationMultiItemResizer.h \
    kImageAnnotator/src/annotations/properties/AnnotationBlurProperties.h \
    kImageAnnotator/src/annotations/properties/AnnotationPathProperties.h \
    kImageAnnotator/src/annotations/properties/AnnotationProperties.h \
    kImageAnnotator/src/annotations/properties/AnnotationBlurProperties.h \
    kImageAnnotator/src/annotations/properties/AnnotationTextProperties.h \
    kImageAnnotator/src/annotations/undo/AddCommand.h \
    kImageAnnotator/src/annotations/undo/ArrangeCommand.h \
    kImageAnnotator/src/annotations/undo/CropCommand.h \
    kImageAnnotator/src/annotations/undo/DeleteCommand.h \
    kImageAnnotator/src/annotations/undo/MoveCommand.h \
    kImageAnnotator/src/annotations/undo/PasteCommand.h \
    kImageAnnotator/src/annotations/undo/ResizeCommand.h \
    kImageAnnotator/src/annotations/undo/ScaleCommand.h \
    kImageAnnotator/src/annotations/undo/UndoStack.h \
    kImageAnnotator/src/backend/Config.h \
    kImageAnnotator/src/common/constants/Constants.h \
    kImageAnnotator/src/common/enum/FillTypes.h \
    kImageAnnotator/src/common/enum/ToolTypes.h \
    kImageAnnotator/src/common/filter/IgnoreShortcutsFilter.h \
    kImageAnnotator/src/common/helper/ConfigNameHelper.h \
    kImageAnnotator/src/common/helper/CursorHelper.h \
    kImageAnnotator/src/common/helper/IconLoader.h \
    kImageAnnotator/src/common/helper/ItemHelper.h \
    kImageAnnotator/src/common/helper/KeyHelper.h \
    kImageAnnotator/src/common/helper/MathHelper.h \
    kImageAnnotator/src/common/helper/ShapeHelper.h \
    kImageAnnotator/src/gui/annotator/AnnotationWidget.h \
    kImageAnnotator/src/gui/annotator/WidgetConfigurator.h \
    kImageAnnotator/src/gui/cropper/CropHandles.h \
    kImageAnnotator/src/gui/cropper/CropSelectionHandler.h \
    kImageAnnotator/src/gui/cropper/CropSelectionMoveHelper.h \
    kImageAnnotator/src/gui/cropper/CropSelectionRestrictor.h \
    kImageAnnotator/src/gui/cropper/CropView.h \
    kImageAnnotator/src/gui/cropper/CropWidget.h \
    kImageAnnotator/src/gui/scaler/ScaleDialog.h \
    kImageAnnotator/src/gui/scaler/ScaleSizeHandler.h \
    kImageAnnotator/src/gui/scaler/ScaleWidget.h \
    kImageAnnotator/src/gui/CoreView.h \
    kImageAnnotator/src/widgets/ColorPicker.h \
    kImageAnnotator/src/widgets/CustomSpinBox.h \
    kImageAnnotator/src/widgets/CustomToolButton.h \
    kImageAnnotator/src/widgets/CustomToolButtonAction.h \
    kImageAnnotator/src/widgets/FillTypePicker.h \
    kImageAnnotator/src/widgets/NumberPicker.h \
    kImageAnnotator/src/widgets/ToolPicker.h \
    kImageAnnotator/src/annotations/items/annotationpolygon.h \
    kImageAnnotator/src/annotations/items/abstractannotationpolygon.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/polygonresizehandles.h \
    kImageAnnotator/src/annotations/items/abstractannotationNumberGroup.h \
    kImageAnnotator/src/annotations/items/annotationNumberGroup.h \
    kImageAnnotator/src/annotations/modifiers/resizeHandles/NumberGroupresizehandles.h

INCLUDEPATH += \
                kImageAnnotator \
                kImageAnnotator/include \
                kImageAnnotator/icons \
                kImageAnnotator/icons/dark \
                kImageAnnotator/icons/light \
                kImageAnnotator \
                kImageAnnotator/src \
                kImageAnnotator/src/annotations \
                kImageAnnotator/src/annotations/core \
                kImageAnnotator/src/annotations/items \
                kImageAnnotator/src/annotations/items/helper \
                kImageAnnotator/src/annotations/misc \
                kImageAnnotator/src/annotations/modifiers \
                kImageAnnotator/src/annotations/modifiers/resizeHandles \
                kImageAnnotator/src/annotations/properties \
                kImageAnnotator/src/annotations/undo \
                kImageAnnotator/src/backend \
                kImageAnnotator/src/common \
                kImageAnnotator/src/common/constants \
                kImageAnnotator/src/common/enum \
                kImageAnnotator/src/common/filter \
                kImageAnnotator/src/common/helper \
                kImageAnnotator/src/gui \
                kImageAnnotator/src/gui/annotator \
                kImageAnnotator/src/gui/cropper \
                kImageAnnotator/src/gui/scaler \
                kImageAnnotator/src/widgets

RESOURCES += \
    kImageAnnotator/icons/kImageAnnotator_icons.qrc

DISTFILES += \
    kImageAnnotator/icons/dark/arrow.svg \
    kImageAnnotator/icons/dark/blur.svg \
    kImageAnnotator/icons/dark/color.svg \
    kImageAnnotator/icons/dark/doubleArrow.svg \
    kImageAnnotator/icons/dark/ellipse.svg \
    kImageAnnotator/icons/dark/fillType.svg \
    kImageAnnotator/icons/dark/fillType_borderAndFill.svg \
    kImageAnnotator/icons/dark/fillType_borderAndNoFill.svg \
    kImageAnnotator/icons/dark/fillType_NoBorderAndNoFill.svg \
    kImageAnnotator/icons/dark/fontSize.svg \
    kImageAnnotator/icons/dark/line.svg \
    kImageAnnotator/icons/dark/markerEllipse.svg \
    kImageAnnotator/icons/dark/markerPen.svg \
    kImageAnnotator/icons/dark/markerRect.svg \
    kImageAnnotator/icons/dark/number.svg \
    kImageAnnotator/icons/dark/pen.svg \
    kImageAnnotator/icons/dark/rect.svg \
    kImageAnnotator/icons/dark/select.svg \
    kImageAnnotator/icons/dark/text.svg \
    kImageAnnotator/icons/dark/textColor.svg \
    kImageAnnotator/icons/dark/width.svg \
    kImageAnnotator/icons/dark/.directory \
    kImageAnnotator/icons/light/arrow.svg \
    kImageAnnotator/icons/light/blur.svg \
    kImageAnnotator/icons/light/color.svg \
    kImageAnnotator/icons/light/doubleArrow.svg \
    kImageAnnotator/icons/light/ellipse.svg \
    kImageAnnotator/icons/light/fillType.svg \
    kImageAnnotator/icons/light/fillType_borderAndFill.svg \
    kImageAnnotator/icons/light/fillType_borderAndNoFill.svg \
    kImageAnnotator/icons/light/fillType_NoBorderAndNoFill.svg \
    kImageAnnotator/icons/light/fontSize.svg \
    kImageAnnotator/icons/light/line.svg \
    kImageAnnotator/icons/light/markerEllipse.svg \
    kImageAnnotator/icons/light/markerPen.svg \
    kImageAnnotator/icons/light/markerRect.svg \
    kImageAnnotator/icons/light/number.svg \
    kImageAnnotator/icons/light/pen.svg \
    kImageAnnotator/icons/light/rect.svg \
    kImageAnnotator/icons/light/select.svg \
    kImageAnnotator/icons/light/text.svg \
    kImageAnnotator/icons/light/textColor.svg \
    kImageAnnotator/icons/light/width.svg \
    kImageAnnotator/icons/light/.directory
